jaffle_shop:
  outputs:
    bigquery:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('KEYFILE') }}"
      location: "{{ env_var('LOCATION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 2
      type: bigquery
  target: bigquery
